[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "github.com/coreos/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master"
  source = "github.com/banzaicloud/operator-sdk"
  # version = "=v0.0.4"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "15.2.0"
