[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.3"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.9.3"

[[constraint]]
  name = "github.com/coreos/operator-sdk"
  branch = "master"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "15.2.0"

[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "10.6.0"
